#!/usr/bin/env node

const http = require('http');
const https = require('https');
const fs = require('fs');

const app = require('./app');

const options = {
    key: fs.readFileSync('ssl/server.key'),
    cert: fs.readFileSync('ssl/server.crt')
};

const httpServer = http.createServer(app);
const httpsServer = https.createServer(options, app);

httpServer.listen(app.get('PORT'), () => { 
    console.log(`Server is running at port ${app.get('PORT')} in ${app.get('env')} enviroment`)
});

httpsServer.listen(4443, () => { 
    console.log(`Server is running at port ${app.get('PORT')} in ${app.get('env')} enviroment`)
});
